<a href="https://colab.research.google.com/github/ReshmaMasutha/Linear-Algebra-The-Coding-Way/blob/main/Diagonalization/Diagonalization_Notebook3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

AssiD3.jpg

**Solution for the problem:**

**Steps to Diagonalize a Matrix:**

1.Compute the eigenvalues and eigenvectors of the matrix A.

2.Form the matrix P using the eigenvectors as columns.

3.Form the diagonal matrix D using the eigenvalues.

4.Verify that A=PDP*-1


In [ ]:
import numpy as np

# Define the matrix A
A = np.array([[1, 3, 3], [-3, -5, -3], [3, 3, 1]])

# Function to diagonalize the matrix A
def diagonalize(A):
    eigenvalues, eigenvectors = np.linalg.eig(A)
    P = eigenvectors
    D = np.diag(eigenvalues)
    return P, D

# Compute P and D
P, D = diagonalize(A)

# Print the results
print("Matrix A:")
print(A)
print("\nMatrix P (Eigenvectors):")
print(P)
print("\nMatrix D (Diagonal matrix of Eigenvalues):")
print(D)


Matrix A:
[[ 1  3  3]
 [-3 -5 -3]
 [ 3  3  1]]

Matrix P (Eigenvectors):
[[ 5.77350269e-01 -1.28197512e-16 -6.72654054e-01]
 [-5.77350269e-01 -7.07106781e-01  7.37141689e-01]
 [ 5.77350269e-01  7.07106781e-01 -6.44876349e-02]]

Matrix D (Diagonal matrix of Eigenvalues):
[[ 1.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0. -2.]]


**1.Define the Matrix A:**

The matrix A is defined as a NumPy array.

**2.Diagonalize Function:**

1.The 'diagonalize' function computes the eigenvalues and eigenvectors of A using NumPy's 'np.linalg.eig' function.

2.It forms the matrix P with the eigenvectors as columns and the diagonal matrix D with the eigenvalues on the diagonal.

**3.Compute P and D:**

Call the diagonalize function with the matrix A to obtain P and D.

**4.Print the Results:**

Print the original matrix A, the matrix P of eigenvectors, and the diagonal matrix D of eigenvalues.

In [ ]:
# Function to perform Gauss-Jordan elimination
def gauss_jordan_inverse(P):
    n = len(P)
    # Create an augmented matrix [P | I]
    augmented_matrix = np.hstack((P, np.identity(n)))

    # Apply Gauss-Jordan elimination
    for i in range(n):
        # Make the diagonal element 1
        diag_element = augmented_matrix[i][i]
        if diag_element == 0:
            for k in range(i + 1, n):
                if augmented_matrix[k][i] != 0:
                    augmented_matrix[[i, k]] = augmented_matrix[[k, i]]
                    break
            diag_element = augmented_matrix[i][i]
        augmented_matrix[i] = augmented_matrix[i] / diag_element

        # Make the other elements in column i zero
        for j in range(n):
            if i != j:
                factor = augmented_matrix[j][i]
                augmented_matrix[j] = augmented_matrix[j] - factor * augmented_matrix[i]

    # Extract the right half as the inverse
    P_inv = augmented_matrix[:, n:]
    return P_inv

# Function to diagonalize the matrix A
def diagonalize(A):
    eigenvalues, eigenvectors = np.linalg.eig(A)
    P = eigenvectors
    D = np.diag(eigenvalues)
    return P, D

# Compute P and D
P, D = diagonalize(A)

# Calculate P^-1 using Gauss-Jordan elimination
P_inv = gauss_jordan_inverse(P)

# Print the results
print("Matrix P (Eigenvectors):")
print(P)
print("\nMatrix P^-1 (Calculated without readymade function):")
print(P_inv)


Matrix P (Eigenvectors):
[[ 5.77350269e-01 -1.28197512e-16 -6.72654054e-01]
 [-5.77350269e-01 -7.07106781e-01  7.37141689e-01]
 [ 5.77350269e-01  7.07106781e-01 -6.44876349e-02]]

Matrix P^-1 (Calculated without readymade function):
[[ 1.73205081  1.73205081  1.73205081]
 [-1.41421356 -1.2786323   0.13558127]
 [ 0.          1.48664829  1.48664829]]


**To find Inverse of P:**

**1.Gauss-Jordan Inverse Function:**


* **'gauss_jordan_inverse(P)'**:
This function computes the inverse of the matrix P using the Gauss-Jordan elimination method.   

* **Augmented Matrix:**
 An augmented matrix is created by horizontally stacking P and an identity matrix of the same size.  

* **Diagonalization:**
 For each row, the diagonal element is made 1 by dividing the entire row by the diagonal element. If the diagonal element is zero, rows are swapped to ensure a non-zero diagonal element.  

* **Zeroing Out Other Elements:**

   1. For each column, other elements are made zero by subtracting the appropriate multiple of the current row.

   2. The right half of the augmented matrix is extracted as the inverse matrix P*−1.

**2.Diagonalize Function:**

This function calculates the eigenvalues and eigenvectors of matrix A, forming P and D.

**3.Calculation and Output:**

The 'gauss_jordan_inverse' function is used to compute P*-1 and print it.

In [ ]:
# Function to perform matrix multiplication
def matrix_multiply(A, B):
    result = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                result[i, j] += A[i, k] * B[k, j]
    return result

# Function to perform Gauss-Jordan elimination to find the inverse
def gauss_jordan_inverse(P):
    n = len(P)
    augmented_matrix = np.hstack((P, np.identity(n)))

    for i in range(n):
        diag_element = augmented_matrix[i][i]
        if diag_element == 0:
            for k in range(i + 1, n):
                if augmented_matrix[k][i] != 0:
                    augmented_matrix[[i, k]] = augmented_matrix[[k, i]]
                    break
            diag_element = augmented_matrix[i][i]
        augmented_matrix[i] = augmented_matrix[i] / diag_element

        for j in range(n):
            if i != j:
                factor = augmented_matrix[j][i]
                augmented_matrix[j] = augmented_matrix[j] - factor * augmented_matrix[i]

    P_inv = augmented_matrix[:, n:]
    return P_inv

# Function to diagonalize the matrix A
def diagonalize(A):
    eigenvalues, eigenvectors = np.linalg.eig(A)
    P = eigenvectors
    D = np.diag(eigenvalues)
    return P, D

# Compute P and D
P, D = diagonalize(A)

# Calculate P^-1 using Gauss-Jordan elimination
P_inv = gauss_jordan_inverse(P)

# Multiply PDP^-1 manually
PD = matrix_multiply(P, D)
PDP_inv = matrix_multiply(PD, P_inv)

# Print the results
print("Matrix A:")
print(A)
print("\nMatrix P (Eigenvectors):")
print(P)
print("\nMatrix D (Diagonal matrix of Eigenvalues):")
print(D)
print("\nMatrix P^-1 (Calculated without readymade function):")
print(P_inv)
print("\nMatrix PDP^-1 (Calculated manually):")
print(PDP_inv)

# Check if PDP^-1 matches A
if np.allclose(A, PDP_inv):
    print("\nPDP^-1 matches A")
else:
    print("\nPDP^-1 does not match A")


Matrix A:
[[ 1  3  3]
 [-3 -5 -3]
 [ 3  3  1]]

Matrix P (Eigenvectors):
[[ 5.77350269e-01 -1.28197512e-16 -6.72654054e-01]
 [-5.77350269e-01 -7.07106781e-01  7.37141689e-01]
 [ 5.77350269e-01  7.07106781e-01 -6.44876349e-02]]

Matrix D (Diagonal matrix of Eigenvalues):
[[ 1.  0.  0.]
 [ 0. -2.  0.]
 [ 0.  0. -2.]]

Matrix P^-1 (Calculated without readymade function):
[[ 1.73205081  1.73205081  1.73205081]
 [-1.41421356 -1.2786323   0.13558127]
 [ 0.          1.48664829  1.48664829]]

Matrix PDP^-1 (Calculated manually):
[[ 1.  3.  3.]
 [-3. -5. -3.]
 [ 3.  3.  1.]]

PDP^-1 matches A


**To find the multiply of PDP*-1:**

**1.Matrix Multiplication Function:**

* 'matrix_multiply(A, B)': This function manually multiplies two matrices A and B. It iterates through each element, computing the dot product of the rows of A with the columns of B.

**2.Gauss-Jordan Inverse Function:**

* **'gauss_jordan_inverse(P)':** This function computes the inverse of matrix P using Gauss-Jordan elimination as explained earlier.

**3.Diagonalize Function:**

* **'diagonalize(A)'**: This function calculates the eigenvalues and eigenvectors of matrix A, forming P and D.

**4.Multiplication and Verification:**

* The code first computes the product PD.

* Then it multiplies PD with P*-1 to get
PDP*−1.

* Finally, it compares PDP*−1 with the original matrix A to check if they are approximately equal.

In [ ]:
# Calculate the determinant of P
det_P = np.linalg.det(P)

# Print the results
print("Matrix P (Eigenvectors):")
print(P)
print("\nDeterminant of P:")
print(det_P)

# Check if the determinant is non-zero
if det_P != 0:
    print("\nThe columns of P are linearly independent.")
else:
    print("\nThe columns of P are not linearly independent.")


Matrix P (Eigenvectors):
[[ 5.77350269e-01 -1.28197512e-16 -6.72654054e-01]
 [-5.77350269e-01 -7.07106781e-01  7.37141689e-01]
 [ 5.77350269e-01  7.07106781e-01 -6.44876349e-02]]

Determinant of P:
-0.27460986748505883

The columns of P are linearly independent.
